// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl_txyEvF57JMryZEw-Xwxvu0yy3ZIALA',
    appId: '1:502860687791:web:d2c49134786f9b70b3e75a',
    messagingSenderId: '502860687791',
    projectId: 'chat-app-5cc82',
    authDomain: 'chat-app-5cc82.firebaseapp.com',
    storageBucket: 'chat-app-5cc82.appspot.com',
    measurementId: 'G-WENYJGJNTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA1o_50Sng-tFzB93b1Qe18jPq5sM6y-U',
    appId: '1:502860687791:android:d19a27b62b83b7e5b3e75a',
    messagingSenderId: '502860687791',
    projectId: 'chat-app-5cc82',
    storageBucket: 'chat-app-5cc82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD84Bxdag3Wgb_UoYmJflGposVaeHnkYvU',
    appId: '1:502860687791:ios:7569eb1fbbef2a9fb3e75a',
    messagingSenderId: '502860687791',
    projectId: 'chat-app-5cc82',
    storageBucket: 'chat-app-5cc82.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD84Bxdag3Wgb_UoYmJflGposVaeHnkYvU',
    appId: '1:502860687791:ios:44bab09050177f13b3e75a',
    messagingSenderId: '502860687791',
    projectId: 'chat-app-5cc82',
    storageBucket: 'chat-app-5cc82.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
